insert into ilces  values (1, 'Umeå',1);
insert into ilces  values (2, 'Chai Nat',1);
insert into ilces  values (3, 'Lubień Kujawski',1);
insert into ilces  values (4, 'Leworook',2);
insert into ilces  values (5, 'Oslo',2);
insert into ilces  values (6, 'Duyun',2);
insert into ilces  values (7, 'Pohonsirih',3);
insert into ilces  values (8, 'Moneghetti',3);
insert into ilces  values (9, 'Veisiejai',3);
insert into ilces  values (10, 'Angkimang',4);
insert into ilces  values (11, 'Mendes',4);
insert into ilces  values (12, 'Senanga',4);
insert into ilces  values (13, 'Shanghuang',5);
insert into ilces  values (14, 'Ipatinga',5);
insert into ilces  values (15, 'Alto Río Senguer',5);
insert into ilces  values (16, 'Rokoy',6);
insert into ilces  values (17, 'Limbuš',6);
insert into ilces  values (18, 'Zhujiachang',6);
insert into ilces  values (19, 'Koutsopódi',7);
insert into ilces  values (20, 'Santa Maria do Souto',7);
insert into ilces  values (21, 'Mê Linh',7);
insert into ilces  values (22, 'Thị Trấn Phù Yên',8);
insert into ilces  values (23, 'Lanxi',8);
insert into ilces  values (24, 'Rimouski',8);
insert into ilces  values (25, 'Zhushan',9);
insert into ilces  values (26, 'Sukahening',9);
insert into ilces  values (27, 'Šentvid pri Stični',9);
insert into ilces  values (28, 'Beppu',10);
insert into ilces  values (29, 'Bigoudine',10);
insert into ilces  values (30, 'Gazojak',10);

